type Session = User | null;
// Generated by https://quicktype.io

type User = {
  id: number;
  name: string;
  username: string;
  email: string;
  address: Address;
  phone: string;
  website: string;
  company: Company;
};

type Address = {
  street: string;
  suite: string;
  city: string;
  zipcode: string;
  geo: Geo;
};

type Geo = {
  lat: string;
  lng: string;
};

type Company = {
  name: string;
  catchPhrase: string;
  bs: string;
};

type Albums = {
  userId: number;
  id: number;
  title: string;
}[];

type AlbumDetail = {
  albumId: number;
  id: number;
  title: string;
  url: string;
  thumbnailUrl: string;
};

type VoidFunction = () => void;

type IdVoidFunction = (id: number) => void;
